In [8]:
import pandas as pd

df = pd.read_excel(r"C:\Users\sonig\Downloads\E-commerce_Dataset.xlsx",sheet_name=None)

print(df.keys())

dict_keys(['customers', 'products', 'orders'])

In [ ]:
# E- commerce Dataset Cleaning
# customers data cleaning process

dict_keys(['customers', 'products', 'orders'])

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   int64
 1   customer_name  4851 non-null   object
 2   email          4606 non-null   object
 3   phone          5000 non-null   object
 4   city           5000 non-null   object
 5   country        4276 non-null   object
dtypes: int64(1), object(5)
memory usage: 234.5+ KB
None

In [9]:
print(df["customers"].head(10))

   customer_id      customer_name                          email  \
0            1       Jacob Garcia               ryan56@yahoo.com
1            2      Robert Fuller               mark28@young.com
2            3   Crystal Hamilton             manuel36@gmail.com
3            4         Eric Welch         jennifer22@hotmail.com
4            5         Alexis Orr           parkmary@skinner.com
5            6    Erik Montgomery                            NaN
6            7      Douglas Perry  scottmiller@blevins-brady.net
7            8  Mr. Michael Allen               xirwin@yahoo.com
8            9       Katie Hunter      tanya89@miller-roman.info
9           10    Daniel Phillips             ahancock@gmail.com

           phone            city country
0     3048482646     Grayborough  Canada
1     5147408332    Michaelburgh  Canada
2     5244341405        Taraberg      UK
3     5461663211     Austinburgh      UK
4     7031525435  Cassandrahaven     NaN
5     5276790793        Coxshire  india
6     6433281205   Thomasborough  Canada
7  invalid_phone       Riggsstad     NaN
8     9651816218     East Adrian  Canada
9     6714243645        Allenton     USA

In [10]:
CT=df["customers"]

In [13]:
print(CT.head(15))

    customer_id      customer_name                          email  \
0             1       Jacob Garcia               ryan56@yahoo.com
1             2      Robert Fuller               mark28@young.com
2             3   Crystal Hamilton             manuel36@gmail.com
3             4         Eric Welch         jennifer22@hotmail.com
4             5         Alexis Orr           parkmary@skinner.com
5             6    Erik Montgomery                            NaN
6             7      Douglas Perry  scottmiller@blevins-brady.net
7             8  Mr. Michael Allen               xirwin@yahoo.com
8             9       Katie Hunter      tanya89@miller-roman.info
9            10    Daniel Phillips             ahancock@gmail.com
10           11   Alexander Cortez    michellestephens@baxter.com
11           12       Dawn Roberts     kari03@russell-sanders.com
12           13      Carlos Massey          langmichelle@cox.info
13           14         Julia Page        michaelgraham@gmail.com
14           15       Brooke Patel               xsmith@smith.com

            phone            city country
0      3048482646     Grayborough  Canada
1      5147408332    Michaelburgh  Canada
2      5244341405        Taraberg      UK
3      5461663211     Austinburgh      UK
4      7031525435  Cassandrahaven     NaN
5      5276790793        Coxshire  india
6      6433281205   Thomasborough  Canada
7   invalid_phone       Riggsstad     NaN
8      9651816218     East Adrian  Canada
9      6714243645        Allenton     USA
10     5775592833                     NaN
11     9761370952      Sherrybury  Canada
12  invalid_phone    Jonathanbury  india
13     5145619745  Lake Levihaven  Canada
14     4998207371     New Jessica     NaN

In [14]:
CT.isnull().sum()

customer_id        0
customer_name    149
email            394
phone              0
city               0
country          724
dtype: int64

In [16]:
CT.duplicated().sum()

np.int64(0)

In [17]:
CT[CT["phone"] == "invalid_phone"]

,customer_id,customer_name,email,phone,city,country
7,8,Mr. Michael Allen,xirwin@yahoo.com,invalid_phone,Riggsstad,NaN
12,13,Carlos Massey,langmichelle@cox.info,invalid_phone,Jonathanbury,india
35,36,Nicholas Vincent,joyce76@novak-santos.com,invalid_phone,New Robert,NaN
42,43,Justin Gates,garciaamanda@wong.biz,invalid_phone,,U.S.A
54,55,Jennifer Anderson,christine22@hotmail.com,invalid_phone,North Nathaniel,UK
...,...,...,...,...,...,...
4936,4937,Matthew Tran,juarezlisa@hotmail.com,invalid_phone,,India
4948,4949,David Collier,NaN,invalid_phone,North Andrew,India
4976,4977,Grant Jones,stephenmorgan@hotmail.com,invalid_phone,Brandonbury,India
4981,4982,Selena Jennings,mmcmillan@lucas.com,invalid_phone,Erikamouth,NaN
4998,4999,Collin Sanchez,matthew04@hotmail.com,invalid_phone,Lake Donald,india

In [19]:
CT["phone"] = CT["phone"].replace("invalid_phone",'')

In [20]:
CT[CT["phone"] == "invalid_phone"]

Empty DataFrame
Columns: [customer_id, customer_name, email, phone, city, country]
Index: []

In [101]:
CT["country"]=CT["country"].str.upper()

In [102]:
CT.head(10)

,customer_id,customer_name,email,phone,city,country
0,1,Jacob Garcia,ryan56@yahoo.com,3048482646,Grayborough,CANADA
1,2,Robert Fuller,mark28@young.com,5147408332,Michaelburgh,CANADA
2,3,Crystal Hamilton,manuel36@gmail.com,5244341405,Taraberg,UK
3,4,Eric Welch,jennifer22@hotmail.com,5461663211,Austinburgh,UK
4,5,Alexis Orr,parkmary@skinner.com,7031525435,Cassandrahaven,NA
5,6,Erik Montgomery,NA,5276790793,Coxshire,INDIA
6,7,Douglas Perry,scottmiller@blevins-brady.net,6433281205,Thomasborough,CANADA
7,8,Mr. Michael Allen,xirwin@yahoo.com,,Riggsstad,NA
8,9,Katie Hunter,tanya89@miller-roman.info,9651816218,East Adrian,CANADA
9,10,Daniel Phillips,ahancock@gmail.com,6714243645,Allenton,USA

In [27]:
CT[CT["country"].isnull()]

Empty DataFrame
Columns: [customer_id, customer_name, email, phone, city, country]
Index: []

In [26]:
CT["country"]=CT["country"].fillna("NA")

In [30]:
CT["email"]=CT["email"].fillna("NA")

In [31]:
CT[CT["email"].isnull()]

Empty DataFrame
Columns: [customer_id, customer_name, email, phone, city, country]
Index: []

In [32]:
CT["customer_name"]=CT["customer_name"].fillna("NA")

In [33]:
CT.isnull().sum()

customer_id      0
customer_name    0
email            0
phone            0
city             0
country          0
dtype: int64

In [42]:
CT.to_csv("new_customer.csv", index=False)

In [41]:
CT["city"]=CT["city"].replace(' ',"NA")

In [43]:
CT.to_csv("new_customer.csv", index=False)

In [44]:
CT.head(20)

,customer_id,customer_name,email,phone,city,country
0,1,Jacob Garcia,ryan56@yahoo.com,3048482646,Grayborough,CANADA
1,2,Robert Fuller,mark28@young.com,5147408332,Michaelburgh,CANADA
2,3,Crystal Hamilton,manuel36@gmail.com,5244341405,Taraberg,UK
3,4,Eric Welch,jennifer22@hotmail.com,5461663211,Austinburgh,UK
4,5,Alexis Orr,parkmary@skinner.com,7031525435,Cassandrahaven,NA
5,6,Erik Montgomery,NA,5276790793,Coxshire,INDIA
6,7,Douglas Perry,scottmiller@blevins-brady.net,6433281205,Thomasborough,CANADA
7,8,Mr. Michael Allen,xirwin@yahoo.com,,Riggsstad,NA
8,9,Katie Hunter,tanya89@miller-roman.info,9651816218,East Adrian,CANADA
9,10,Daniel Phillips,ahancock@gmail.com,6714243645,Allenton,USA
10,11,Alexander Cortez,michellestephens@baxter.com,5775592833,,NA
11,12,Dawn Roberts,kari03@russell-sanders.com,9761370952,Sherrybury,CANADA
12,13,Carlos Massey,langmichelle@cox.info,,Jonathanbury,INDIA
13,14,Julia Page,michaelgraham@gmail.com,5145619745,Lake Levihaven,CANADA
14,15,Brooke Patel,xsmith@smith.com,4998207371,New Jessica,NA
15,16,Carlos Rubio,cohenbrooke@hotmail.com,7037595570,Jenniferton,INDIA
16,17,Holly Duarte,xmedina@yahoo.com,7623897181,North Soniatown,USA
17,18,Samuel Clark,gpope@hotmail.com,3091131744,West Mallory,USA
18,19,Jane Macdonald,huynhgabriel@yahoo.com,8037806992,Port Edwin,INDIA
19,20,Ian Garrison,hollandmegan@sims.com,7772169073,New Maria,NA

In [45]:
CT["city"]=CT["city"].replace(' ',"NA")

In [46]:
CT.to_csv("new_customers.csv", index=False)

In [ ]:
# products data cleaning process

In [49]:
print(df["products"].head())

   product_id              book_title     genre    price  stock  \
0           1           Provide born.    SCI-FI  4938.16    142
1           2  Single collection use.       NaN  4278.52    251
2           3           Then popular.  fiction   3999.13    322
3           4        New real office.   History  3634.28    332
4           5    Western rather half.   Romance  2422.25    367

   published_year
0          2018.0
1          2020.0
2          2023.0
3          2022.0
4          2020.0

In [50]:
PDT=df["products"]

In [51]:
PDT.isnull().sum()

product_id          0
book_title          0
genre             484
price               0
stock               0
published_year    237
dtype: int64

In [55]:
PDT.duplicated().sum()

np.int64(0)

In [57]:
PDT[PDT["genre"].isnull()]

,product_id,book_title,genre,price,stock,published_year
1,2,Single collection use.,NaN,4278.52,251,2020.0
11,12,Property order it soon.,NaN,474.34,183,NaN
17,18,Purpose something.,NaN,1900.80,238,2023.0
27,28,White along reflect.,NaN,333.61,112,2020.0
31,32,Talk surface.,NaN,41.01,355,2022.0
...,...,...,...,...,...,...
1989,1990,Blue bad.,NaN,4941.98,-1,2022.0
1990,1991,Arm century bad anything.,NaN,1991.25,246,2019.0
1993,1994,Business generation above.,NaN,460.67,273,2035.0
1994,1995,Again.,NaN,460.14,231,2019.0
1999,2000,Action speech campaign.,NaN,857.38,267,2022.0

In [69]:
PDT["genre"] = PDT["genre"].fillna("NA")

In [59]:
PDT[PDT["genre"].isnull()]

Empty DataFrame
Columns: [product_id, book_title, genre, price, stock, published_year]
Index: []

In [61]:
print(PDT.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      2000 non-null   int64
 1   book_title      2000 non-null   object
 2   genre           2000 non-null   object
 3   price           2000 non-null   float64
 4   stock           2000 non-null   int64
 5   published_year  1763 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 93.9+ KB
None

In [64]:
PDT["published_year"]=PDT["published_year"].fillna(PDT["published_year"].median())

In [67]:
PDT["genre"] = PDT["genre"].str.title()

In [78]:
PDT["genre"]=PDT["genre"].replace('Na',"NA")

In [79]:
print(PDT.head(20))

    product_id                      book_title     genre    price  stock  \
0            1                   Provide born.    Sci-Fi  4938.16    142
1            2          Single collection use.        NA  4278.52    251
2            3                   Then popular.  Fiction   3999.13    322
3            4                New real office.   History  3634.28    332
4            5            Western rather half.   Romance  2422.25    367
5            6           Politics institution.   History  2931.08    330
6            7                 Play while car.   Romance  4475.53    370
7            8               Without ago rate.    Sci-Fi  1650.78    425
8            9             First threat whole.  Fiction   3402.02     76
9           10             Media office front.   Romance  1732.16    144
10          11                      Any human.  Fiction    230.61    313
11          12         Property order it soon.        NA   474.34    183
12          13                     Group wear.  Fiction   3349.00    381
13          14         Candidate listen would.    Sci-Fi  1280.56    416
14          15                  Effort police.   Romance  3669.55    372
15          16                     Our system.  Fiction   2884.85    362
16          17                Stuff operation.   History   550.96    325
17          18              Purpose something.        NA  1900.80    238
18          19         Sea bed herself street.    Sci-Fi   820.65    311
19          20  Friend relationship media out.   Romance  1131.41    319

    published_year
0           2018.0
1           2020.0
2           2023.0
3           2022.0
4           2020.0
5           2018.0
6           2018.0
7           2022.0
8           2022.0
9           2020.0
10          2019.0
11          2021.0
12          2021.0
13          2023.0
14          2021.0
15          2021.0
16          2021.0
17          2023.0
18          2020.0
19          2021.0

In [80]:
PDT.to_csv("new_products.csv", index=False)

In [81]:
# orders data cleaning process

In [83]:
OD = df["orders"]

In [92]:
print(OD.head(20))

    order_id  customer_id  product_id  quantity order_date      status  \
0          1         3747         949        -1 2025-03-13          NA
1          2         1927        1565         3 2024-11-04     Pending
2          3          362        1331         3 2025-01-14  completed
3          4          825         361         7 2024-05-13   Completed
4          5         2023         470         1 2025-07-15   Cancelled
5          6         2927         642         6 2025-01-17          NA
6          7         3098        1547         9 2025-12-07   Cancelled
7          8         4278        1773        -1 2023-11-28  completed
8          9         3412         786        10 2024-10-07   Cancelled
9         10         1516         353        -1 2025-08-26     Pending
10        11         1213        2150         3 2024-12-26   Completed
11        12         2920        1910         0 2025-11-24   Completed
12        13         2366         328         3 2023-08-28   Cancelled
13        14         2717         795         9 2025-02-18     Pending
14        15         1820        1153         1 2024-09-24     Pending
15        16         1922        1867         2 2025-06-19     Pending
16        17         2707        1103        -1 2024-10-03     Pending
17        18         3864        1275         6 2023-07-25   Cancelled
18        19         3529        1583         1 2023-07-24   Completed
19       167          135         222         4 2024-04-24   Completed

    payment_amount
0         12668.10
1           529.46
2         14324.92
3         14749.07
4          6589.09
5         10867.45
6         13042.74
7          1949.41
8          1405.60
9         14352.03
10        14921.19
11         8075.25
12        12456.61
13         4861.50
14         8506.98
15         -163.62
16         5915.10
17        12935.37
18         1097.30
19         2477.56

In [85]:
OD.isnull().sum()

order_id             0
customer_id          0
product_id           0
quantity             0
order_date           0
status            3092
payment_amount       0
dtype: int64

In [86]:
OD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        15000 non-null  int64
 1   customer_id     15000 non-null  int64
 2   product_id      15000 non-null  int64
 3   quantity        15000 non-null  int64
 4   order_date      15000 non-null  datetime64[ns]
 5   status          11908 non-null  object
 6   payment_amount  15000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 820.4+ KB

In [88]:
OD.duplicated().sum()

np.int64(0)

In [90]:
OD["status"] = OD["status"].fillna("NA")

In [93]:
OD["status"] = OD["status"].str.strip().str.title()

In [98]:
print(OD.head(20))

    order_id  customer_id  product_id  quantity order_date     status  \
0          1         3747         949         4 2025-03-13         NA
1          2         1927        1565         3 2024-11-04    Pending
2          3          362        1331         3 2025-01-14  Completed
3          4          825         361         7 2024-05-13  Completed
4          5         2023         470         1 2025-07-15  Cancelled
5          6         2927         642         6 2025-01-17         NA
6          7         3098        1547         9 2025-12-07  Cancelled
7          8         4278        1773         4 2023-11-28  Completed
8          9         3412         786        10 2024-10-07  Cancelled
9         10         1516         353         4 2025-08-26    Pending
10        11         1213        2150         3 2024-12-26  Completed
11        12         2920        1910         0 2025-11-24  Completed
12        13         2366         328         3 2023-08-28  Cancelled
13        14         2717         795         9 2025-02-18    Pending
14        15         1820        1153         1 2024-09-24    Pending
15        16         1922        1867         2 2025-06-19    Pending
16        17         2707        1103         4 2024-10-03    Pending
17        18         3864        1275         6 2023-07-25  Cancelled
18        19         3529        1583         1 2023-07-24  Completed
19       167          135         222         4 2024-04-24  Completed

    payment_amount
0         12668.10
1           529.46
2         14324.92
3         14749.07
4          6589.09
5         10867.45
6         13042.74
7          1949.41
8          1405.60
9         14352.03
10        14921.19
11         8075.25
12        12456.61
13         4861.50
14         8506.98
15         -163.62
16         5915.10
17        12935.37
18         1097.30
19         2477.56

In [95]:
OD["status"] = OD["status"].replace("Na","NA")

In [97]:
OD["quantity"] = OD["quantity"].replace(-1,OD["quantity"].median())

In [107]:
CT.isnull().sum()

customer_id      0
customer_name    0
email            0
phone            0
city             0
country          0
dtype: int64

In [105]:
PDT.isnull().sum()

product_id        0
book_title        0
genre             0
price             0
stock             0
published_year    0
dtype: int64

In [106]:
OD.isnull().sum()

order_id          0
customer_id       0
product_id        0
quantity          0
order_date        0
status            0
payment_amount    0
dtype: int64

In [109]:
OD.to_csv("new_orders.csv", index=False)